os: linux
files:
  - source: /
    destination:  /home/ec2-user/legalLankanFrontend-app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
      
  BeforeInstall:
    - location: scripts/install_dependencies1.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
      
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root